site_name: Dokumentace Roští.cz
pages:
    - Domů: index.md
    - "Základní informace": base.md
    - "DNS a registrace domén": dns.md
    - "Základní pojmy": aword.md
    - "E-mailové schránky": emails.md
    - "Migrace e-mailů z Roští": end_of_emails.md
    - "SSH přístup": ssh.md
    - "SSL certifikáty": ssl.md
    - "Staré Roští": old.md
    - Aplikace:
        - Úvod: apps/index.md
        - PHP: apps/php.md
        - Python: apps/python.md
        - Node: apps/node.md
        - Ruby: apps/ruby.md
    - Úložiště:
#        - Úvod: storages/index.md
        - MongoDB: storages/mongo.md
        - Memcached: storages/memcached.md
        - Redis: storages/redis.md
    - Nástroje:
        - Supervisor: tools/supervisor.md
        - Cron: tools/cron.md
        - "Doinstalování Node.js": addnode.md
        - "Doinstalování balíčků": extra-packages.md
    - "O nás": about.md
    - "FAQ - časté dotazy": faq.md
theme: readthedocs
markdown_extensions:
  - admonition