site_name: Dokumentace Roští.cz
pages:
    - Domů: index.md
    - "Základní informace": base.md
    - "DNS a registrace domén": dns.md
    - Aplikace:
        - Úvod: apps/index.md
        - PHP: apps/php.md
        - Python: apps/python.md
        - Node: apps/node.md
#        - Ruby: apps/ruby.md
    - Úložiště:
#        - Úvod: storages/index.md
        - Memcached: storages/memcached.md
        - Redis: storages/redis.md
    - Cron: cron.md
    - "O nás": about.md
theme: readthedocs
