site_name: Dokumentace Roští.cz
pages:
    - Domů: index.md
    - "Základní informace": base.md
    - "DNS a registrace domén": dns.md
    - Aplikace:
        - PHP: apps/php.md
        - Python: apps/python.md
        - Node: apps/node.md
    - Úložiště: storages/index.md
    - Cron: cron.md
    - "O nás": about.md
theme: readthedocs
