name: Build+Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.
    - uses: actions/setup-python@v1
    - uses: dschep/install-pipenv-action@v1
    - name: Build
      run: |
        pipenv install mkdocs
        pipenv run mkdocs build
    - name: Deploy
      env:
        SSHKEY: ${{ secrets.deploy_ssh_key }}
        HOST: ${{ secrets.host }}
        PORT: ${{ secrets.port }}
      run: |
        rsync -avz -e "ssh -i ssh.key -oStrictHostKeyChecking=no -p $PORT" site/ app@$HOST:/srv/app/
